# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cp05_protocol_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 646)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 30, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox_19 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout.addWidget(self.checkBox_20)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 70, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.checkBox_21 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_2.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_2.addWidget(self.checkBox_22)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_4.setText(_translate("Form", "1"))
        self.pushButton_5.setText(_translate("Form", "1"))
