# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ct67_update_firmware_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_Form(object):
    def setupUi(self, update_Form):
        update_Form.setObjectName("update_Form")
        update_Form.resize(400, 242)
        self.gridLayoutWidget = QtWidgets.QWidget(update_Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sent_file_pushbutton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sent_file_pushbutton.setObjectName("sent_file_pushbutton")
        self.gridLayout.addWidget(self.sent_file_pushbutton, 1, 1, 1, 1)
        self.select_file_pushbutton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_file_pushbutton.setObjectName("select_file_pushbutton")
        self.gridLayout.addWidget(self.select_file_pushbutton, 0, 1, 1, 1)
        self.path_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.path_lineedit.setObjectName("path_lineedit")
        self.gridLayout.addWidget(self.path_lineedit, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(update_Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 200, 361, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(update_Form)
        QtCore.QMetaObject.connectSlotsByName(update_Form)

    def retranslateUi(self, update_Form):
        _translate = QtCore.QCoreApplication.translate
        update_Form.setWindowTitle(_translate("update_Form", "Form"))
        self.sent_file_pushbutton.setText(_translate("update_Form", "发送固件"))
        self.select_file_pushbutton.setText(_translate("update_Form", "选择固件"))
